- id: sourcemeta-jsonschema-lint
  name: sourcemeta-jsonschema-lint
  description: Lint JSON or YAML schema files
  entry: jsonschema lint
  language: system
  types_or: [json, yaml]
  minimum_pre_commit_version: 2.9.0
