name: JSON Schema CLI
description: Install the JSON Schema CLI
runs:
  using: composite
  steps:
    - name: Install the JSON Schema CLI (latest)
      shell: bash
      run: |
        curl --retry 5 --location --fail-early --silent --show-error \
          --output "${GITHUB_WORKSPACE}/install.sh" \
          "https://raw.githubusercontent.com/intelligence-ai/jsonschema/main/install"
        chmod +x "${GITHUB_WORKSPACE}/install.sh"
        "${GITHUB_WORKSPACE}/install.sh" 0.2.0
        rm "${GITHUB_WORKSPACE}/install.sh"
