# See https://documentation.ubuntu.com/snapcraft/stable/reference/project-file/snapcraft-yaml
name: jsonschema
base: core22
adopt-info: jsonschema
summary: The command-line tool for working with JSON Schema
description: |
  Covers formatting, linting, testing, bundling, and more for both local development and CI/CD pipelines.
grade: stable
confinement: strict
apps:
  jsonschema:
    command: usr/local/bin/jsonschema
    completer: usr/local/share/bash-completion/completions/jsonschema
    # Means users can only run it on HOME
    plugs: [ home, network ]
parts:
  jsonschema:
    plugin: cmake
    source: .
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE:STRING=Release
    override-pull: |
      craftctl default
      craftctl set version="$(tr -d '\n\r' < VERSION)"
